MVCApp.EndPoints/Controllers/UserTaskController.cs
using App.Domain.Core.TaskManager.ResultAggrigate.Entity;
using App.Domain.Core.TaskManager.TaskAggrigate.Contracts;
using App.Domain.Core.TaskManager.TaskAggrigate.Entity;
using App.Domain.Core.TaskManager.UserAggrigate.Entity;
using App.Domain.Services.TaskManager.UserTaskServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using MVCApp.EndPoints.Models;

namespace MVCApp.EndPoints.Controllers;

[Authorize]
public class UserTaskController : Controller
{
    private readonly IUserTaskAppService _userTaskAppService;
    private readonly UserManager<AppUser> _userManager;
    public UserTaskController(IUserTaskAppService userTaskAppService, UserManager<AppUser> userManager)
    {
        _userTaskAppService = userTaskAppService;
        _userManager = userManager;
    }

    public async Task<IActionResult> TaskList(CancellationToken cancel)
    {
        var user = await _userManager.GetUserAsync(User);
        var tasks = await _userTaskAppService.GetAllUserTasksAsync(user.Id, cancel);
        ViewBag.TaskCount = tasks.Count();

        return View(tasks);
    }
    
    public async Task<IActionResult> Delete(int id, CancellationToken cancel)
    {
        var user = await _userManager.GetUserAsync(User);
         var task = await _userTaskAppService.GetUserTaskAsync(user.Id, id, cancel);
        if (task == null)
        {
            TempData["TaskNotFound"] = "Task not found";
            return RedirectToAction("TaskList");
        }

        Result result = await _userTaskAppService.DeleteUserTaskAsync(task, cancel);
        if (result.Flag)
        {
            TempData["DeleteResult"] = "Task deleted successfully";
           return RedirectToAction("TaskList");
        }
        

        TempData["DeleteResult"] = "Logic Error";
        return RedirectToAction("TaskList");
    }

    [HttpGet]
    public async Task<IActionResult> Add()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Add(AddTaskModelView addTaskModelView, CancellationToken cancel)
    {
        if (!ModelState.IsValid)
            return View(addTaskModelView);
        var user = await _userManager.GetUserAsync(User);
        var result = await _userTaskAppService.CheckUserTaskLimitAsync(user.Id, cancel);

        if (!result.Flag)
        {
            TempData["TaskLimit"] = result.Message;
            return View(addTaskModelView);
        }

        var userTask = new UserTask()
        {
            Title = addTaskModelView.Title,
            DeadTime = addTaskModelView.DeadTime,
            Description = addTaskModelView.Description,
        };

        var result2 = await _userTaskAppService.AddUserTaskAsync(user.Id,userTask, cancel);

        if (result2.Flag)
        {
            TempData["AddResult"] = result2.Message;
            return View(addTaskModelView);
        }

            TempData["AddResult"] = result2.Message;
            return View();
        
    }

    [HttpGet]
    public async Task<IActionResult> Update(int id, CancellationToken cancel)
    {
        var user = await _userManager.GetUserAsync(User);
        var task = await _userTaskAppService.GetUserTaskAsync(user.Id, id, cancel);
        if (task == null)
        {
            TempData["UpdateMessage"] = "Task not found";
            return RedirectToAction("Update");
        }
        var taskModel = new UpdateTaskModelView
        {
            Id = task.Id,
            Title = task.Title,
            Description = task.Description,
            DeadTime = task.DeadTime,
            IsCompelete = task.IsCompleted
        };

        return View(taskModel);
    }


    [HttpPost]
    public async Task<IActionResult> Update(UpdateTaskModelView updateTaskModelView, CancellationToken cancel)
    {
        if(!ModelState.IsValid)
            return View(updateTaskModelView);
        var user = await _userManager.GetUserAsync(User);

        var taskExist = await _userTaskAppService.GetUserTaskAsync(user.Id, updateTaskModelView.Id, cancel);
        if (taskExist == null)
        {
            TempData["FoundTask"] = "Task not found";
            return View(updateTaskModelView);
        }

        taskExist.Title = updateTaskModelView.Title;
        taskExist.Description = updateTaskModelView.Description;
        taskExist.DeadTime = updateTaskModelView.DeadTime;
        taskExist.IsCompleted = updateTaskModelView.IsCompelete;

        var result = await _userTaskAppService.UpdateUserTaskAsync(user.Id,taskExist, cancel);

        if (result.Flag)
            return RedirectToAction("TaskList");

        TempData["UpdateResult"] = result.Message;
        return RedirectToAction("TaskList");
    }
}

MVCApp.EndPoints/Views/UserTask/Add.cshtml
@model AddTaskModelView
<div class="container px-5 my-5">
    <form method="post" asp-action="Add" id="contactForm" data-sb-form-api-token="API_TOKEN">

        <div class="form-floating mb-3">
            <input class="form-control" asp-for="Title" />
            <label asp-for="Title"></label>
            <span class="text-danger" asp-validation-for="Title"></span>
        </div>

        

        <div class="form-floating mb-3">
            <textarea class="form-control" asp-for="Description" type="text" style="height: 10rem;"></textarea>
            <label asp-for="Description">Description</label>
            <span class="text-danger" asp-validation-for="Description"></span>
        </div>

        <div class="form-floating mb-3">
            <input class="form-control" asp-for="DeadTime"/>
            <label asp-for="DeadTime">Exam Date</label>
            <span class="text-danger" asp-validation-for="DeadTime"> </span>
        </div>


        <div class="d-none" id="submitErrorMessage">
            <div class="text-center text-danger mb-3">Error sending message!</div>
        </div>
        <div class="d-grid">
            <button class="btn btn-primary btn-lg " id="submitButton" type="submit">Submit</button>
        </div>
    </form>
   
</div>
@if (TempData["TaskLimit"] is not null){
    <div class="alert alert-info">@TempData["TaskLimit"]</div>
}

@if (TempData["AddResult"] is not null)
{
    <div class="alert alert-info">@TempData["AddResult"]</div>
}

@section Scripts
{
    <partial name="_validationScriptsPartial" />
}

<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

MVCApp.EndPoints/Views/UserTask/TaskList.cshtml
@using App.Domain.Core.TaskManager.TaskAggrigate.Entity

@model List<UserTask>

<div class="container mt-4">
    @{
        if (TempData["TaskNotFound"] is not null)
        {
            <div class="alert alert-info">@TempData["TaskNotFound"]</div>
        }
        else if (TempData["DeleteResult"] is not null){
            <div class="alert alert-Success">@TempData["TaskNotFound"]</div>
        }
    }
    
    <h2 class="text-center mb-4"> User Tasks List (@ViewBag.TaskCount)</h2>
    <table class="table table-striped table-bordered table-hover text-center align-middle">
        <thead class="table-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Descriptionr</th>
                <th scope="col">IsCompleted</th>
                <th scope="col">RegisterTime</th>
                <th scope="col">DeadTime</th>
                <th scope="col">Actions</th> 
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.Id</th>
                        <td>@item.Title</td>
                        <td>@item.Description</td>
                        <td>@item.IsCompleted</td>
                        <td>@item.RegisterTime </td>
                        <td>@item.DeadTime</td>
                        <td>
                             <a asp-controller="UserTask" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Update</a>
                            <form asp-action="Delete" method="post" style="display:inline;"
                                  onsubmit="return confirm('Are you sure you want to delete this user?');">
                                <input type="hidden" name="id" value="@item.Id" />
                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            </form> 
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="10" class="text-center text-danger">No Users Available.</td>
                </tr>
            }
        </tbody>
    </table>
</div>

MVCApp.EndPoints/Views/UserTask/Update.cshtml
@model UpdateTaskModelView
<div class="container px-5 my-5">
    <form method="post" asp-action="Update" id="contactForm" data-sb-form-api-token="API_TOKEN">

        <input type="hidden" asp-for="Id" />
        <div class="form-floating mb-3">
            <input class="form-control" asp-for="Title" />
            <label asp-for="Title"></label>
            <span class="text-danger" asp-validation-for="Title"></span>
        </div>



        <div class="form-floating mb-3">
            <textarea class="form-control" asp-for="Description" type="text" style="height: 10rem;"></textarea>
            <label asp-for="Description">Description</label>
            <span class="text-danger" asp-validation-for="Description"></span>
        </div>

        <div class="form-floating mb-3">
            <input class="form-control" asp-for="DeadTime" />
            <label asp-for="DeadTime">DeadTime</label>
            <span class="text-danger" asp-validation-for="DeadTime"> </span>
        </div>

        <div class="mb-3">
            <label class="form-label d-block">status</label>
            <div class="form-check form-check-inline">
                <input class="form-check-input" asp-for="IsCompelete" value="true" type="checkbox" id="completed"   />
                <label class="form-check-label" for="completed">Completed</label>
            </div>

            <div class="form-check form-check-inline">
                <input class="form-check-input" asp-for="IsCompelete" value="false" id="uncompleted" type="checkbox"  />
                <label class="form-check-label" for="uncompleted">Uncompleted</label>
            </div>
        </div>

        <span class="text-danger" asp-validation-for="IsCompelete"></span>

        <div class="d-none" id="submitErrorMessage">
            <div class="text-center text-danger mb-3">Error sending message!</div>
        </div>
        <div class="d-grid">
            <button class="btn btn-primary btn-lg " id="submitButton" type="submit">Submit</button>
        </div>
    </form>

</div>



    @{

    if (TempData["FoundTask"] is not null)
    {
        <div class="alert alert-info">@TempData["FoundTask"]</div>
    }
    else if (TempData["UpdateResult"] is not null)
    {
        <div class="alert alert-info">@TempData["UpdateResult"]</div>
    }
    
    }
    TempData["UpdateResult"]
    @section Scripts
    {
        <partial name="_validationScriptsPartial" />
    }

    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>